# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b572ff73af15a325fead1e65b94a6c4d8fb710c42ae5abbeddef1234556c65be1c66d27523c015570cb4c5ea897fcc469cc04059a7ba7a66adb3be1ddf8f2eef

test:
  secret_key_base: 6f8acc68ca93649318c312a08474311af6c88414d5290374c9f8d5e05979eb508f0923880864cbb4a2fb6450e6e637c17cc105a5fb08e8057a0206b8545b5543

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>